// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package connector

import (
	"database/sql"

	"github.com/google/uuid"
)

type Project struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	IsActive    bool
	IsDeleted   bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
