// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: project.sql

package connector

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertIntoProject = `-- name: InsertIntoProject :one
insert into project (id, name, description, is_active, is_deleted, created_at, updated_at)
values (default, $1, $2, default, default, default, default)
returning id
`

type InsertIntoProjectParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) InsertIntoProject(ctx context.Context, arg InsertIntoProjectParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertIntoProject, arg.Name, arg.Description)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
